---
- name: Docker init swarm
  yum:
    state: latest
    update_cache: yes
- name: Worker token from manager swarm node 
  debug:
      msg: "Worker token 1 is {{ hostvars['worker_token1']['token'] }}"  