---
- name: Create a carts_swarm _overlay container
  docker_container:
         name: carts
         image: eu.gcr.io/united-aura-252016/carts:latest
         command: "--spring.data.mongodb.host=mgdb" 
         state: started
         detach: yes
         interactive: yes
         recreate: yes
         tty: no
         pull: true
         published_ports: 8081:80

- name: Attach network overlay
  shell: "docker network connect shop-socks carts"

- name: Clean up Docker unused images
  docker_prune:
        images: yes
        images_filters:
               dangling: true                                                         