---
- hosts: pd
  become: true
  gather_facts: no
   tasks:
  - name: Update apt index
    apt:
      state: latest
      update_cache: yes
      force_apt_get: yes
  - name: Install docker dependencies
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnup2
      - software-properties-common
  - name: Docker key      
    apt_key: 
        url=https://download.docker.com/linux/debian/gpg 
        state: present
  - name: Apt add docker repo
    apt_repository: deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable
       state: present
       file: docker
  - name: Update apt index
    apt:
      state: latest
      update_cache: yes
      force_apt_get: yes
   - name: "APT - install 'docker-ce'"
     apt:
      name: "docker-ce"
      state: latest
      update_cache: yes
  - name: 'enable docker systemd service'
    service:
      name: 'docker'
      state: 'started'
      enabled: 'yes'
  - name: 'add users to docker group'
    user:
      name: 'buildserver'
      groups: 'docker'
      append: 'yes'



            
- hosts: db
  become: true
  gather_facts: no
   tasks:
  - name: Update yum index
    yum:
      state: latest
      update_cache: yes
      force_apt_get: yes
  - name: Install docker dependencies
    yum: name={{ item }} state=latest update_cache=yes
    with_items:
      - yum-utils
      - device-mapper-persistent-data 
      - lvm2
  - name: Yum add docker repo
    get_url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  - name: "YUM - install 'docker-ce'"
     package:
      name: "docker-ce"
      state: latest
  - name: 'enable docker systemd service'
    service:
      name: 'docker'
      state: 'started'
      enabled: 'yes'
  - name: 'add users to docker group'
    user:
      name: 'buildserver'
      groups: 'docker'
      append: 'yes'

  - name: Creating user 
