---
- hosts: db
  become: true
  gather_facts: yes
  roles:
  - docker_engine_swarm
    
- hosts: pd
  become: true
  gather_facts: yes
  roles:
  - docker_engine_swarm
  
#- hosts: docker_swarm_mngr
#  become: true
#  roles:
#  - docker_run_services
  
#- hosts: docker_swarm_worker
#  become: true
#  roles: 
#  - docker_run_services