---
- name: Create a mgdb_swarm _overlay container for carts microservice
  docker_container:
        name: mgdb
        image: eu.gcr.io/united-aura-252016/mgdb:latest 
        state: started
        pull: true
        recreate: yes
        networks:
            - name: shop-socks
        published_ports: 27017:27017
        volumes:
            - Garts_Mongodb:/data/db

- name: Clean up Docker unused images
  docker_prune:
        images: yes
        images_filters:
              dangling: true   