---
- name: Create a mysql_swarm _overlay container for catalogue
  docker_container:
        name: catalogue-db
        image: eu.gcr.io/united-aura-252016/cataloguedb:latest 
        state: started
        pull: true
        recreate: yes
        published_ports: 
            - 3306:3306 
            - 33060:33060
        networks:
            - name: shop-socks
        volumes:
            - Catalogue_Mysql:/var/lib/mysql

- name: Clean up Docker unused images
  docker_prune:
        images: yes
        images_filters:
              dangling: true   